### ISSUE TITLE
ChatGPT error 400

### ISSUE THREAD

**Issue by devyujie** [Ice-Hazymoon/openai-scf-proxy#1]
配合 [chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web/issues/249) 使用，看到腾讯云日志也显示调用成功，但是web端报错，这个是哪边的问题呢
![image](https://user-images.githubusercontent.com/48620527/223066343-8e1796a6-424d-47fd-8c03-13717ed39aa2.png)

![image](https://user-images.githubusercontent.com/48620527/223066276-bb916422-2c40-4246-9527-8d70756f494d.png)

**Comment by Ice-Hazymoon** [comment]
你的 apiBaseUrl 是怎么写的呢

**Comment by devyujie** [comment]
![image](https://user-images.githubusercontent.com/48620527/223068099-422bb3d8-615d-46ae-96f9-9d3cecbbc0af.png)

**Comment by devyujie** [comment]
已发送，感谢大佬！

**Comment by Ice-Hazymoon** [comment]
有 chatgpt-web 的部署地址吗，你发送的部署方面没有问题

**Comment by devyujie** [comment]
我本地部署的..我先求助下那边，谢谢

**Comment by Ice-Hazymoon** [comment]
可以试试使用最新的代码包或者修改 app.js，我去掉了 /chat 这个目录，应该会兼容性好一些

**Comment by delicacyyy** [comment]
![image](https://user-images.githubusercontent.com/11476249/223141529-2bd484b7-b037-4a73-b047-5dc69dae8169.png)
跑在vscode里面会卡住 这是怎么回事呢

**Comment by Ice-Hazymoon** [comment]
> ![image](https://user-images.githubusercontent.com/11476249/223141529-2bd484b7-b037-4a73-b047-5dc69dae8169.png) 跑在vscode里面会卡住 这是怎么回事呢

没用过这个插件，不过既然能有回答，后面卡住就是网络问题了
