### ISSUE TITLE
python调用的一个建议

### ISSUE THREAD

**Issue by BoboBruce98** [Ice-Hazymoon/openai-scf-proxy#11]
实测在python调用的话,需要在访问地址后面加上/v1
也就是
openai.api_base = 'https://serviceXXXXXX.tencentcs.com/v1'
这样子才可以通过.
总之,谢谢楼主解决这个问题.
话说,还没搞懂腾讯云函数的计费方式.

**Comment by Ice-Hazymoon** [comment]
我不知道你用的是什么python 程序，代理的是 openai 根域名，如果要加上 /v1，可能是程序处理的问题
计费方式可以看腾讯云的文档，
