### ISSUE TITLE
权限问题报错

### ISSUE THREAD

**Issue by ffvaadvaddvd** [Ice-Hazymoon/openai-scf-proxy#12]
【获取回答失败：Your access was terminated due to violation of our policies, please check your email for more information. If you believe this is in error and would like to appeal, please contact [support@openai.com](mailto:support@openai.com).】

**Comment by Ice-Hazymoon** [comment]
你使用的是自己的key吗

**Comment by ffvaadvaddvd** [comment]
是的，自己的

**Comment by Ice-Hazymoon** [comment]
你检查下你的 OpenAI 账号状态是否正常
