### ISSUE TITLE
自托管问题

### ISSUE THREAD

**Issue by WM-MXBG** [Ice-Hazymoon/openai-scf-proxy#13]
请问自托管运行后怎么使用啊，项目运行不运行进入 https://ai.okmiku.com/ 网站不用输入接口地址也能使用，求指教

**Comment by Ice-Hazymoon** [comment]
托管在自己的服务器上，然后找一个支持设置 OpenAI 地址的项目就能用了，有问题可继续留言

**Comment by WM-MXBG** [comment]
> 托管在自己的服务器上，然后找一个支持设置 OpenAI 地址的项目就能用了，有问题可继续留言

抱歉，这方面有些小白，我看app.js里是对api.openai.com的一个api请求， 但是请求完怎么应用我还是不太懂，https://ai.okmiku.com/ 这个网站我进入不用像云函数那样输入接口地址也能用，我不清楚这是什么原理，这个自托管不像云函数有个最终可用链接，我就懵了

**Comment by WM-MXBG** [comment]
> 托管在自己的服务器上，然后找一个支持设置 OpenAI 地址的项目就能用了，有问题可继续留言

就像 https://ai.okmiku.com/ 这个网页，自托管和它之间怎么配合使用的原理我还是不清楚，云函数是输入接口地址，自托管什么也没用

**Comment by WM-MXBG** [comment]
> 托管在自己的服务器上，然后找一个支持设置 OpenAI 地址的项目就能用了，有问题可继续留言

看其它评论我知道怎么用了，就是我把 http:/公网地址:9000 当接口地址放上去后会获取答案失败
