### ISSUE TITLE
小白求教

### ISSUE THREAD

**Issue by rzdxp15** [Ice-Hazymoon/openai-scf-proxy#18]
我把代理服务器部署了得到一个网址，然后我怎么使用啊，就直接用这个公网地址代替http：//openai.api。com
吗

**Comment by yizhenfeng2016** [comment]
yes

**Comment by WM-MXBG** [comment]
> yes

请问得到的 http://公网地址:9000 这个地址是还需要做什么权限处理吗，我直接把网址放到接口地址上会获取答案失败

**Comment by yizhenfeng2016** [comment]
不需要，将你的云函数那个地址代替
![image](https://user-images.githubusercontent.com/28002527/223683253-bed90680-b867-4756-8732-58aa66e98a7b.png)

**Comment by WM-MXBG** [comment]
> 不需要，将你的云函数那个地址代替 ![image](https://user-images.githubusercontent.com/28002527/223683253-bed90680-b867-4756-8732-58aa66e98a7b.png)

我使用 http://公网地址:9000 代替了云函数作为接口地址的输入，但是会得到
![image](https://user-images.githubusercontent.com/57312972/223684071-859e2349-fb2c-4d41-bdc3-609324161388.png)
这种结果

**Comment by yizhenfeng2016** [comment]
账号被封了吧，你的代理是放在国内，还是国外？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月8日(周三) 晚上6:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ice-Hazymoon/openai-scf-proxy] 小白求教 (Issue #18)




  
不需要，将你的云函数那个地址代替 
  
我使用 http://公网地址:9000 代替了云函数作为接口地址的输入，但是会得到
 
 这种结果

**Comment by WM-MXBG** [comment]
> 账号被封了吧，你的代理是放在国内，还是国外？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月8日(周三) 晚上6:06 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Ice-Hazymoon/openai-scf-proxy] 小白求教 (Issue #18) 不需要，将你的云函数那个地址代替 我使用 http://公网地址:9000 代替了云函数作为接口地址的输入，但是会得到 这种结果 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请问您说的是chatgpt的账号还是腾讯云账号？代理我用clash开的规则模式（本机开，不是服务器），需要服务器国外代理？

**Comment by yizhenfeng2016** [comment]
代理部署在国外。因为国内访问http://openai.api.com会被墙，所有需要代理，就是先访问代理（国外），通过代理访问http://openai.api.com得到结果。所有如果你部署在本地，跟直接访问http://openai.api.com没有什么区别，都会被墙

**Comment by WM-MXBG** [comment]
> 代理部署在国外。因为国内访问[http://openai.api.com会被墙，所有需要代理，就是先访问代理（国外），通过代理访问http://openai.api.com得到结果。所有如果你部署在本地，跟直接访问http://openai.api.com没有什么区别，都会被墙](http://openai.api.com%E4%BC%9A%E8%A2%AB%E5%A2%99%EF%BC%8C%E6%89%80%E6%9C%89%E9%9C%80%E8%A6%81%E4%BB%A3%E7%90%86%EF%BC%8C%E5%B0%B1%E6%98%AF%E5%85%88%E8%AE%BF%E9%97%AE%E4%BB%A3%E7%90%86%EF%BC%88%E5%9B%BD%E5%A4%96%EF%BC%89%EF%BC%8C%E9%80%9A%E8%BF%87%E4%BB%A3%E7%90%86%E8%AE%BF%E9%97%AEhttp://openai.api.com%E5%BE%97%E5%88%B0%E7%BB%93%E6%9E%9C%E3%80%82%E6%89%80%E6%9C%89%E5%A6%82%E6%9E%9C%E4%BD%A0%E9%83%A8%E7%BD%B2%E5%9C%A8%E6%9C%AC%E5%9C%B0%EF%BC%8C%E8%B7%9F%E7%9B%B4%E6%8E%A5%E8%AE%BF%E9%97%AEhttp://openai.api.com%E6%B2%A1%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB%EF%BC%8C%E9%83%BD%E4%BC%9A%E8%A2%AB%E5%A2%99)

那寄了，我的服务器是国内的，也没有国外vps，顶多有个本机机场

**Comment by WM-MXBG** [comment]
> 代理部署在国外。因为国内访问[http://openai.api.com会被墙，所有需要代理，就是先访问代理（国外），通过代理访问http://openai.api.com得到结果。所有如果你部署在本地，跟直接访问http://openai.api.com没有什么区别，都会被墙](http://openai.api.com%E4%BC%9A%E8%A2%AB%E5%A2%99%EF%BC%8C%E6%89%80%E6%9C%89%E9%9C%80%E8%A6%81%E4%BB%A3%E7%90%86%EF%BC%8C%E5%B0%B1%E6%98%AF%E5%85%88%E8%AE%BF%E9%97%AE%E4%BB%A3%E7%90%86%EF%BC%88%E5%9B%BD%E5%A4%96%EF%BC%89%EF%BC%8C%E9%80%9A%E8%BF%87%E4%BB%A3%E7%90%86%E8%AE%BF%E9%97%AEhttp://openai.api.com%E5%BE%97%E5%88%B0%E7%BB%93%E6%9E%9C%E3%80%82%E6%89%80%E6%9C%89%E5%A6%82%E6%9E%9C%E4%BD%A0%E9%83%A8%E7%BD%B2%E5%9C%A8%E6%9C%AC%E5%9C%B0%EF%BC%8C%E8%B7%9F%E7%9B%B4%E6%8E%A5%E8%AE%BF%E9%97%AEhttp://openai.api.com%E6%B2%A1%E6%9C%89%E4%BB%80%E4%B9%88%E5%8C%BA%E5%88%AB%EF%BC%8C%E9%83%BD%E4%BC%9A%E8%A2%AB%E5%A2%99)

谢谢您的解惑
