### ISSUE TITLE
公益一下，5月到期

### ISSUE THREAD

**Issue by chaos-zhu** [Ice-Hazymoon/openai-scf-proxy#19]
http://52.229.229.71:9000【香港IP有封号风险，停止使用，晚点分享个美国的上来!!!】

**Comment by Ryan2009** [comment]
> > 
> 
> 小水管，适度使用

404 了

**Comment by Ryan2009** [comment]
> > 
> 
> 小水管，适度使用

可用。感谢共享

**Comment by bebestmaple** [comment]
已不可用

**Comment by chaos-zhu** [comment]
> 

服务一直正常......

一般主要就俩API：
查询余额：[get] 【可以浏览器直接访问下面API，如果返回的内容是`Incorrect API key provided......`，则服务正常】
http://52.229.229.71:9000/dashboard/billing/credit_grants

聊天交互：[post]
http://52.229.229.71:9000/v1/chat/completions
