### ISSUE TITLE
提个醒吧~

### ISSUE THREAD

**Issue by colinkyo** [Ice-Hazymoon/openai-scf-proxy#24]
【Due to this breach we are halting access to the API immediately for the organization Personal. Common reasons for breach include violations of our content policy, repeated attempts at disallowed use-cases, or accessing the API from an unsupported location. You may also wish to review our Terms of Use.】这样做，尤其是用香港ip 。会导致封号。我就是这样测试了一两天。号就封了。唯一能猜到的原因就是unsupported location！

**Comment by chaos-zhu** [comment]
原来是这原因，我的刚被封了...    thx
