### ISSUE TITLE
好像无法支持 stream 流式输出

### ISSUE THREAD

**Issue by xylagbx** [Ice-Hazymoon/openai-scf-proxy#26]
我将云函数的代理地址填入 [yetone/openai-translator: 基于 ChatGPT API 的划词翻译浏览器插件和跨平台桌面端应用](https://github.com/yetone/openai-translator) 后，无法实现 stream 流式输出，使用 https://api.openai.com 是可以的，能问一下是什么原因吗？

**Comment by Ice-Hazymoon** [comment]
腾讯的问题，可以试试自托管或者 Cloudflare Worker 

![image](https://user-images.githubusercontent.com/25239977/223956186-3df4d664-6596-4d03-9eb0-d91e2b881f07.png)

**Comment by Monica-lee99** [comment]
> 腾讯的问题，可以试试自托管或者 Cloudflare Worker
> 
> ![image](https://user-images.githubusercontent.com/25239977/223956186-3df4d664-6596-4d03-9eb0-d91e2b881f07.png)

自托管，自己的服务器需要是海外的吗

**Comment by jijiechen** [comment]
没有这个功能，腾讯云那实在是太坑爹了
