### ISSUE TITLE
这个方案不支持streaming mode

### ISSUE THREAD

**Issue by cnericxu** [Ice-Hazymoon/openai-scf-proxy#32]
谢谢分享，配置完成后使用yetone大佬的openai-translator发现不能像以前一样使用streaming mode逐字出来翻译结果，而是要等好多秒一次性出来翻译结果了，有点难受

**Comment by lzz29** [comment]
你部署到自己的服务器上就支持了
腾讯云那边不支持

**Comment by Chef5** [comment]
streaming mode能出来一部分，排查了半天，原来问题出在这🙃
