### ISSUE TITLE
为什么会一直报433呢

### ISSUE THREAD

**Issue by ysh199882** [Ice-Hazymoon/openai-scf-proxy#4]
![image](https://user-images.githubusercontent.com/76462784/223121281-4c7bb04b-546e-4144-9378-11f8202becaf.png)
为什么会一直报433呢

**Comment by Ice-Hazymoon** [comment]
你是用的哪个 ChatGPT 服务，我去试试

**Comment by ysh199882** [comment]
麻烦大佬了，https://service-cpxgk86g-1311320559.hk.apigw.tencentcs.com/release/v1/chat/completions

> 你是用的哪个 ChatGPT 服务，我去试试

**Comment by Ice-Hazymoon** [comment]
你用的哪个 ChatGPT 软件呢

**Comment by ysh199882** [comment]
> 

我自己搭了一个，woyaorun.cn

**Comment by Ice-Hazymoon** [comment]
我测试正常啊，你用的什么浏览器，用隐身模式试试。

![image](https://user-images.githubusercontent.com/25239977/223144480-4715ef1e-7fa0-4d61-aecb-f88d6332c6f5.png)

**Comment by ysh199882** [comment]
> 我测试正常啊，你用的什么浏览器，用隐身模式试试。
> 
> ![image](https://user-images.githubusercontent.com/25239977/223144480-4715ef1e-7fa0-4d61-aecb-f88d6332c6f5.png)

重复对话三次后就会报433😂

**Comment by ysh199882** [comment]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/76462784/223146440-89b4bb46-b970-4902-b32c-af714ee16c99.png">
时好时坏😂

**Comment by Ice-Hazymoon** [comment]
我测试了一下好像确实是这样，你再试试用我的：[https://service-icewi6dg-1252310422.hk.apigw.tencentcs.com/](https://service-icewi6dg-1252310422.hk.apigw.tencentcs.com/)  链接后面不需要加任何东西

**Comment by ysh199882** [comment]
> 我测试了一下好像确实是这样，你再试试用我的：https://service-icewi6dg-1252310422.hk.apigw.tencentcs.com/ 链接后面不需要加任何东西

重新部署了，麻烦大佬再看下🙏

**Comment by Ice-Hazymoon** [comment]
为什么链接后面有 `release` 啊，把这一段去掉
![image](https://user-images.githubusercontent.com/25239977/223155361-4358c483-9a77-4bc4-b528-024388ef4026.png)

**Comment by ysh199882** [comment]
> 为什么链接后面有 `release` 啊，把这一段去掉 ![image](https://user-images.githubusercontent.com/25239977/223155361-4358c483-9a77-4bc4-b528-024388ef4026.png)

去掉了，还是不行😭

**Comment by Ice-Hazymoon** [comment]
你搭建云函数的时候，执行超时时间 有设置吗

![image](https://user-images.githubusercontent.com/25239977/223165998-5abdbb9b-64f8-4f37-b4df-c6dd381e7ac8.png)

**Comment by ysh199882** [comment]
大佬能请你喝杯咖啡吗？超级感谢你的帮助🙏

**Comment by Ice-Hazymoon** [comment]
哈哈，谢谢，但不用了，能帮到你很荣幸

**Comment by Ice-Hazymoon** [comment]
话说你用的这个项目有开源吗，我在文档里标注一下

**Comment by aehyok** [comment]
@Ice-Hazymoon @ysh199882  大佬请问怎么解决的

**Comment by ysh199882** [comment]
> 话说你用的这个项目有开源吗，我在文档里标注一下

还没有开源，代码写太烂了😂
