### ISSUE TITLE
本人猴子，这样子咋办

### ISSUE THREAD

**Issue by xeKapw** [Ice-Hazymoon/openai-scf-proxy#43]
按教程走的，就是有腾讯云配置那里上传zip后，要我提示改端口9000什么的，也不知道哪里改就没改。然后我好像把代理地址（已经去掉release了）放我的chatgpt的程序里面用不了提示invalid URL，直接点腾讯云里给的访问路径链接是这样，感觉是腾讯云里面出问题就来问问
```
{
  "error": {
    "message": "Invalid URL (GET /)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**Comment by 7457994** [comment]
这样就好了

**Comment by Monkiesh** [comment]
我也是猴子，在https://ai.okmiku.com/网页上总是提示error403

**Comment by crazyjack44** [comment]
> 我也是猴子，在[https://ai.okmiku.com/网页上总是提示error403](https://ai.okmiku.com/%E7%BD%91%E9%A1%B5%E4%B8%8A%E6%80%BB%E6%98%AF%E6%8F%90%E7%A4%BAerror403)

请问你解决了吗？我也是这种情况QAQ。
