### ISSUE TITLE
访问路径一直为：访问路径触发别名：undefined

### ISSUE THREAD

**Issue by neohob** [Ice-Hazymoon/openai-scf-proxy#5]
访问路径一直为：访问路径触发别名：undefined

**Comment by Ice-Hazymoon** [comment]
触发器按照下面的设置

![image](https://user-images.githubusercontent.com/25239977/223142099-1334bfe8-67a7-4f7b-9c9b-a832f89bc293.png)

**Comment by adflasher** [comment]
访问路径有了，但是访问后显示如下，似乎还是不成功。
{
  "error": {
    "message": "Invalid URL (GET /)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by Ice-Hazymoon** [comment]
直接访问会报错，需要配合其他支持代理的软件使用
