### ISSUE TITLE
部署一直提示 404

### ISSUE THREAD

**Issue by binfooo** [Ice-Hazymoon/openai-scf-proxy#6]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/67949953/223157400-2b005b52-3c8e-4c34-89ec-02c3f8374e14.png">

**Comment by Ice-Hazymoon** [comment]
访问根目录404 是正常的，试试访问 https://servicexxxxx.hk.apigw.tencentcs.com/v1/chat/completions ，如果出现 You didn't provide an API key. You need to provide your API key in an Authorization header using xxx 就说明部署成功了

**Comment by binfooo** [comment]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/67949953/223171108-7f97acea-7fc4-4f4c-b2b7-f22d6b795bc6.png">
你好，有办法通过接口调用吗？

**Comment by binfooo** [comment]
GET 请求，带 param 仍然提示需要参数

**Comment by Ice-Hazymoon** [comment]
把完整的请求信息用 curl 或者 fetch 发出来看看

**Comment by binfooo** [comment]
http://service-xxxx.hk.apigw.tencentcs.com/v1/chat/completions?model=text-davinci-003&prompt=xxxxx&temperature=0.7&max_tokens=2048&top_p=1&frequency_penalty=0&presence_penalty=0

**Comment by Ice-Hazymoon** [comment]
OpenAI 的接口只支持 POST 请求

**Comment by binfooo** [comment]
{
    "error": {
        "message": "Invalid URL (POST /v1/chat/completions)",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

POST 请求直接报错这个

**Comment by binfooo** [comment]
![image](https://user-images.githubusercontent.com/67949953/223331995-d8e20107-113d-4456-b503-7be849eb6175.png)

**Comment by Ice-Hazymoon** [comment]
如果可以，你把你云函数的地址私发给：imiku.me@gmail.com 我测试一下

**Comment by binfooo** [comment]
邮件已发送，十分感谢～

**Comment by Ice-Hazymoon** [comment]
还没收到，垃圾箱也没有，你那边发送成功了吗。或者再试试 QQ 邮箱：1733708055@qq.com

**Comment by Ice-Hazymoon** [comment]
你提供的地址是正常使用的，可能是你的请求内容写错了

![image](https://user-images.githubusercontent.com/25239977/223333852-22ee0153-f068-4ab3-a61b-a03900a51221.png)

如果是postman，可以参考下面的参数

![image](https://user-images.githubusercontent.com/25239977/223334067-af2f4ba5-3891-40f8-90c4-5add5ec4cf0c.png)

**Comment by Ryan2009** [comment]
> 访问根目录404 是正常的，试试访问 https://servicexxxxx.hk.apigw.tencentcs.com/v1/chat/completions ，如果出现 You didn't provide an API key. You need to provide your API key in an Authorization header using xxx 就说明部署成功了

那我报的就是这个错了。接下来咋弄呀？借助类似软件指的是？

**Comment by Ice-Hazymoon** [comment]
@Ryan2009 

> > 访问根目录404 是正常的，试试访问 https://servicexxxxx.hk.apigw.tencentcs.com/v1/chat/completions ，如果出现 You didn't provide an API key. You need to provide your API key in an Authorization header using xxx 就说明部署成功了
> 
> 那我报的就是这个错了。接下来咋弄呀？借助类似软件指的是？

有许多开源的 ChatGPT 软件都支持设置 OpenAI 代理，但我没用过所以不好回答，如果找不到的话可以使用文档下方的 https://ai.okmiku.com
