### ISSUE TITLE
按此设置，但是没有成功，访问后显示如下信息

### ISSUE THREAD

**Issue by adflasher** [Ice-Hazymoon/openai-scf-proxy#8]
{
  "error": {
    "message": "Invalid URL (GET /)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by Ryan2009** [comment]
我也是一样的错误
{
  "error": {
    "message": "Invalid URL (GET /)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}

**Comment by Ice-Hazymoon** [comment]
直接访问会报错，这只是一个代理服务，你需要配合其他软件使用

**Comment by adflasher** [comment]
您提到的其他软件，该如何设置呢？怎样才能制作成web版本的，浏览器可以访问的？
