### ISSUE TITLE
使用api模式回答很短就中断，是正常的么？

### ISSUE THREAD

**Issue by boyfoo** [Ice-Hazymoon/openai-scf-proxy#9]
![b27c0a5568a1bbf405ab302226b43ed](https://user-images.githubusercontent.com/29603067/223346777-a747ac08-dcc1-4081-aca2-6d12033d7015.png)
![b0a2411feca0a16509af87319b6633a](https://user-images.githubusercontent.com/29603067/223346791-047bea09-9875-4f98-9af6-b34bb60ac74c.png)

tokens已经设置到最大了

**Comment by aehyok** [comment]
我好像也遇到了同样的问题

**Comment by Ice-Hazymoon** [comment]
方便的话把你部署后的云函数发我邮箱，我研究研究: imiku.me@gmail.com

**Comment by aehyok** [comment]
@Ice-Hazymoon @boyfoo 好像跟那个云函数执行 超时时间有关系，我设置大了好像会好很多

**Comment by Ice-Hazymoon** [comment]
@boyfoo  @aehyok 按照教程里超时时间设置900秒
